import { ItemName } from '../../shared';

const knownGoodPickupItems: ItemName[] = [
  'Poison (item)',
  'Fish food',
  "Monk's robe top",
  "Monk's robe",
];

const allF2pNonWildernessItemPickups: ItemName[] = [
  'Leather boots',
  'Leather gloves',
  'Logs',
  'Knife',
  'Jug',
  'Bowl',
  'Pot',
  'Bucket',
  'Cabbage',
  'Onion',
  'Potato',
  'Egg',
  'Feather',
  'Bronze arrow#(unp)',
  'Bronze dagger#(unp)',
  'Air rune',
  'Water rune',
  'Earth rune',
  'Fire rune',
  'Mind rune',
  'Body rune',
  'Pie dish',
  'Thread',
  'Spade',
  'Brass necklace',
  'Gold bar',
  "Red spiders' eggs",
  'Bones',
  'Tomato',
  'Cheese',
  'Bronze bolts#Unpoisoned',
  'White apron',
  'Banana',
  'Shears',
  'Wine of zamorak',
  'Small fishing net',
  'Tiara mould',
  'Necklace mould',
  'Ring mould',
  'Holy mould'
];

export const allF2pWildernessItemPickups: ItemName[] = [
  'Chaos rune',
  'Iron bar',
  'Cake tin',
  'Plank',
  'Crossbow',
  'Iron dagger#(unp)',
  'Iron med helm',
  'Steel dagger#(unp)',
  'Steel sword',
  'Iron kiteshield',
  'Gold ore',
  'Steel platelegs',
  'Iron scimitar',
  'Nature rune',
  'Steel platebody',
  'Staff of earth',
  'Gold necklace',
  'Sapphire',
  'Cosmic rune',
];

export const allF2pPickupItems: ItemName[] = [
  ...knownGoodPickupItems,
  ...allF2pNonWildernessItemPickups,
  ...allF2pWildernessItemPickups,
];
