import { ItemId } from '../shared';

const knownGoodPickupItems = [
  ItemId['Poison (item)'],
  ItemId['Fish food'],
  ItemId["Monk's robe top"],
  ItemId["Monk's robe"],
];

const allF2pNonWildernessItemPickups = [
  ItemId['Leather boots'],
  ItemId['Leather gloves'],
  ItemId['Logs'],
  ItemId['Knife'],
  ItemId['Jug'],
  ItemId['Bowl'],
  ItemId['Pot'],
  ItemId['Bucket'],
  ItemId['Cabbage'],
  ItemId['Onion'],
  ItemId['Potato'],
  ItemId['Egg'],
  ItemId['Feather'],
  ItemId['Bronze arrow#(unp)'],
  ItemId['Bronze dagger#(unp)'],
  ItemId['Air rune'],
  ItemId['Water rune'],
  ItemId['Earth rune'],
  ItemId['Fire rune'],
  ItemId['Mind rune'],
  ItemId['Body rune'],
  ItemId['Pie dish'],
  ItemId['Thread'],
  ItemId['Spade'],
  ItemId['Brass necklace'],
  ItemId['Gold bar'],
  ItemId["Red spiders' eggs"],
  ItemId['Bones'],
  ItemId['Tomato'],
  ItemId['Cheese'],
  ItemId['Bronze bolts#Unpoisoned'],
  ItemId['White apron'],
  ItemId['Banana'],
  ItemId['Shears'],
  ItemId['Wine of zamorak'],
];

export const allF2pWildernessItemPickups = [
  ItemId['Chaos rune'],
  ItemId['Iron bar'],
  ItemId['Cake tin'],
  ItemId['Plank'],
  ItemId['Crossbow'],
  ItemId['Iron dagger#(unp)'],
  ItemId['Iron med helm'],
  ItemId['Steel dagger#(unp)'],
  ItemId['Steel sword'],
  ItemId['Iron kiteshield'],
  ItemId['Gold ore'],
  ItemId['Steel platelegs'],
  ItemId['Iron scimitar'],
  ItemId['Nature rune'],
  ItemId['Steel platebody'],
  ItemId['Staff of earth'],
  ItemId['Gold necklace'],
  ItemId['Sapphire'],
  ItemId['Cosmic rune'],
];

export const allF2pPickupItems = [
  ...knownGoodPickupItems,
  ...allF2pNonWildernessItemPickups,
  ...allF2pWildernessItemPickups,
];
